### ISSUE TITLE
MissingReferenceException when changing scenes

### ISSUE THREAD

**Issue by twheinen** [prime31/ZestKit#1]
This might be intended behavior, but changing scenes when a tween is playing will result in a MissingReferenceException every frame. Enabling the babysitter bool does get rid of the exceptions, but it leads me to believe the tween is still being checked every frame even though the tweened object doesn't exist. The only other solution I can think of is just making sure all tweens are stopped before changing scenes, but then I would have to keep a reference to every tween I use in the code. It would be great if either all tweens were stopped upon changing scenes, or if there was an easy way to stop all currently running tweens at once. Other than that, ZestKit has been awesome! Thanks!

**Comment by prime31** [comment]
A couple commits ago a stopAllTweens method was added. The next update will have an option to do it automatically when a new level loads. 

Mike

On Apr 28, 2015, at 5:32 PM, Tim Heinen notifications@github.com wrote:

This might be intended behavior, but changing scenes when a tween is playing will result in a MissingReferenceException every frame. Enabling the babysitter bool does get rid of the exceptions, but it leads me to believe the tween is still being checked every frame even though the tweened object doesn't exist. The only other solution I can think of is just making sure all tweens are stopped before changing scenes, but then I would have to keep a reference to every tween I use in the code. It would be great if either all tweens were stopped upon changing scenes, or if there was an easy way to stop all currently running tweens at once. Other than that, ZestKit has been awesome! Thanks!

**Comment by twheinen** [comment]
Wow, thanks for the fast response! The removeAllTweensOnLevelLoad fixed my problem. I didn't realize I had to use ZestKit.instance to access the functions, but now I can see there was a stopAllTweens. Thanks again Mike.
