### ISSUE TITLE
ActionTask issue 1

### ISSUE THREAD

**Issue by yonoslaw** [prime31/ZestKit#10]
This will make "task b" never fire. The action task inside Func will be removed right after being created.

// --------------------------------------------------------
  ActionTask task;

  void Start ()
  {
    task = ActionTask.afterDelay (2f, this, f => {
      print ("task a");
      Func ();
    });
  }

  void Func ()
  {
    ActionTask.afterDelay (3f, this, ff => {
      print ("task b");
    });

```
task.stop ();
```

  }

**Comment by prime31** [comment]
Fixed by commit 4e6689e0e2082427bd444571ebdeebc8b71c6ef8
