### ISSUE TITLE
ActionTask issue

### ISSUE THREAD

**Issue by yonoslaw** [prime31/ZestKit#19]
ActionTask.afterDelay (0.0f, this, task => {
  Debug.Log ("tick");
});

Will run the task each frame forever. I think it should run the task on current or next frame once.

**Comment by prime31** [comment]
ActionTasks don't ever stop until you stop them. If you just call task.stop in your Action it will just run once.

**Comment by yonoslaw** [comment]
Well, if you put delay >0.0 it will run only once. It was like this some
time ago, today I did update the lib and got this sort of error.

2016-04-18 17:26 GMT+02:00 Mike notifications@github.com:

> ActionTasks don't ever stop until you stop them. If you just call
> task.stop in your Action it will just run once.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/prime31/ZestKit/issues/19#issuecomment-211431015

## 

Pozdrawiam,
Seweryn Pańczyniak
