### ISSUE TITLE
No RemoveTweensWithTarget

### ISSUE THREAD

**Issue by yonoslaw** [prime31/ZestKit#2]
Please add something like RemoveTweensWithTarget from GoKit.

**Comment by prime31** [comment]
ZestKit is quite a bit different than GoKit. There isn't a direct correlation of target types like GoKit has. The ZestKit class itself doesn't really know or care about what it is ticking and ticks things that arent even tweens. You can, however, set a context (via setContext) on any tween then find all the tweens with that context to stop them (allTweensWithContext method). You could wrap that up in a simple extension method if you do that often. Actually, I just added the (fully untested) stopAllTweensWithContext method if you want to give it a go.

**Comment by prime31** [comment]
Edit: turns out this was pretty trivial to add so it will be in the next push.
