### ISSUE TITLE
TweenParty SetEaseType does not apply to subtweens.

### ISSUE THREAD

**Issue by arloistale** [prime31/ZestKit#24]
Hey there, I just started using ZestKit, and tried to make use of TweenParty for multiple simultaneous tweens. I want the tweening to be linear (no easing). However, setting there seems to be a default easing on Tweens and if I use setEaseType it has no effect. Here's my code:

```
_highlightParty = new TweenParty(0.4f);

_highlightParty.addTween(transform.ZKlocalScaleTo(new Vector3(2.5f, 2.5f, 1f)));
_highlightParty.addTween(_spriteRenderer.ZKalphaTo(0f));

_highlightParty.setEaseType(EaseType.Linear);

_highlightParty.start();
```

If I use the Tweens individually and use setEaseType(EaseType.Linear) then they will both tween with no easing.

Need insight on this if possible!

**Comment by prime31** [comment]
All fixed! TweenParty was doing its own thing and not working according to the XML doc. Now it is doing things the way the XML doc states them.
