### ISSUE TITLE
Feature request: tween.setUpdateHandler();

### ISSUE THREAD

**Issue by omid3098** [prime31/ZestKit#27]
We had this in GoKit but i can not find the equivalent in ZestKit.
Did you used other method to accomplish this functionality?

**Comment by prime31** [comment]
ZestKit doesn't have update ticks. It is a bit higher performance than GoKit so it tried to do as little as possible in its tick method. What is your use case for needing to know when each tick occurs? It seems like if you need to do something per tick you might as well just do the tween yourself with the Zest class.

**Comment by omid3098** [comment]
Thanks, I rather have performance and do ticks with separate Boolean and my own Monobehaviour Update method.
