### ISSUE TITLE
Changing the scene while tweening

### ISSUE THREAD

**Issue by omid3098** [prime31/ZestKit#29]
when tweening a transform, if i change the scene, this error happens:

> MissingReferenceException: The object of type 'Transform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Transform.set_position (Vector3 value) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:27)
Prime31.ZestKit.TransformVector3Tween.setTweenedValue (Vector3 value) (at Assets/Scripts/Libs/ZestKit/TweenTargets/TransformVector3Tween.cs:35)
Prime31.ZestKit.TransformVector3Tween.updateValue () (at Assets/Scripts/Libs/ZestKit/TweenTargets/TransformVector3Tween.cs:103)
Prime31.ZestKit.Tween`1[UnityEngine.Vector3].tick () (at Assets/Scripts/Libs/ZestKit/Tweens/Tween.cs:195)
Prime31.ZestKit.ZestKit.Update () (at Assets/Scripts/Libs/ZestKit/ZestKit.cs:140)

can zestkit auto stop tweens on object disable/destroy or i have to check that manually?
thanks ;)

**Comment by prime31** [comment]
ZestKit doesn't know you objects lifetime. You can try enabling the babysitter on the ZestKit object which will null check every tick. There is also an option to stop all tweens on level load built in.
