### ISSUE TITLE
Object stops after only 1 loop

### ISSUE THREAD

**Issue by Nesh108** [prime31/ZestKit#35]
Hello!

I have been playing around with ZestKit (awesome btw!) and I am trying to have an object just follow a set of points forever. Here is my current code:

```
    [SerializeField] private ZestSplineSettings Path;
    [SerializeField] private float DurationLoop;
    [SerializeField] private float DelayBetweenLoops;

    void Start()
    {
        new SplineTween(gameObject.transform, new Spline(Path.Nodes), DurationLoop)
            .setLoops(LoopType.RestartFromBeginning, -1, DelayBetweenLoops)
            .start();
    }
```

I put `-1` as in GoKit that was the way for having it run forever. I also tried with `int.MaxValue` and it still stops after 1 round.
What am I doing wrong? :thinking:

**Comment by prime31** [comment]
I can't seem to repro this. Changing the `ZestKitSplineDemo` from the included demo scenes to the following results in a (near) endless loop:

```csharp
            new SplineTween(quad, spline, _duration)
                .setLoops(LoopType.RestartFromBeginning, int.MaxValue)
                .start();
```

**Comment by Nesh108** [comment]
Weird, I tried again and it works.
I guess the problem was `-1f`.

Btw, just an extra question: I have set the path to be `Bezier Path`, how do I tell the Tween that it should be a bezier path as well? I noticed that it doesn't seem to follow precisely the purple path shown in the editor.

**Comment by prime31** [comment]
The `BezierSplineSolver` gets used only when asked for and if there are enough nodes. You can see [here](https://github.com/prime31/ZestKit/blob/master/Assets/ZestKit/Splines/Spline.cs#L118) where it would get instantiated if all the ifs pass.

**Comment by Nesh108** [comment]
Awesome! I missed the parameter in the `new Spline()` constructor. I'll close the issue, thank you :)
