### ISSUE TITLE
Cannot put ZestKit inside Plugins folder

### ISSUE THREAD

**Issue by CreepGin** [prime31/ZestKit#4]
After a fresh import into the Plugins folder:

```
Assets/Plugins/ZestKit/Editor/ZestKitDLLMaker.cs(6,17): error CS0234: The type or namespace name `CSharp' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?
```

Works fine when it's not in Plugins. I tested this on Windows 7 with Unity 5.1.0f2.

**Comment by prime31** [comment]
I haven't come up with a good solution for this one yet. For some reason Unity doesn't include the Csharp namespace for the Plugins/Editor folder. What I have been doing for my projects is just deleting the file (it's only purpose is to create ZestKit DLLs for those that need them).

Mike

On Jun 4, 2015, at 11:04 PM, CreepGin notifications@github.com wrote:

After a fresh import into the Plugins folder:

Assets/Plugins/ZestKit/Editor/ZestKitDLLMaker.cs(6,17): error CS0234: The type or namespace name `CSharp' does not exist in the namespace`Microsoft'. Are you missing an assembly reference?
Works fine when it's not in Plugins. I tested this on Windows 7 with Unity 5.1.0f2.

**Comment by CreepGin** [comment]
Right, I went to test this out after reading your blog post on using submodules in the Plugins folder. I think one solution is to move the Editor folder out of the ZestKit folder.

**Comment by prime31** [comment]
I forgot to mention that this was fixed in a previous commit. Most folks dont need the DLL maker so using it now involves a bit of extra setup explained in the ZestKitDLLMaker file.
