### ISSUE TITLE
feature request: TweenParty/Chain.ContainsTweens or .GetNumberOfTweens

### ISSUE THREAD

**Issue by AniMittra** [prime31/ZestKit#6]
I am using TweenChains containing TweenParties as a timeline system or animation queue to queue up tweens for a puzzle game. During some turns some of the TweenParties don't have any tweens inside them, because that action didn't occur that turn. It would be nice to check with a boolean value if a TweenParty or TweenChain contains any tweens inside it, or even get the number of tweens it has.

Since they are both founded on Lists I think it should be pretty simple to add, but there could be something I haven't considered as I haven't used this library much yet.

use case could be:

``` C#
TweenParty removeGemsParty = new TweenParty(1.0f);
TweenChain rootChain; = new TweenChain();

// some code that adds tweens to removeGemsParty if we removed gems this turn

if (removeGemsParty.ContainsTweens)
{
    rootChain.appendTween(removeGemsParty);
}

rootChain.start();

```

Please let me know if there's already a way to do this that I missed or if you decide to add it in. I can work around it but it would be cool to have.

**Comment by prime31** [comment]
Easy enough. I just added a totalTweens property to both classes.
