### ISSUE TITLE
Chain can't modify same property

### ISSUE THREAD

**Issue by yonoslaw** [prime31/ZestKit#9]
chain.appendTween(Text.transform.ZKlocalScaleTo(Vector3.one \* 1.3f,0.5f));
  chain.appendTween(Text.transform.ZKlocalScaleTo(Vector3.one \* 1.0f,0.5f));
  chain.start();

This should make the transform scale to 1.3 and then back to 1.0. It seems like the second tween is initialized when created so it is from 1.0 to 1.0.
I was unable to do something like this using neither chains nor any other tools inside ZestKit.

**Comment by prime31** [comment]
Tweens in chains are initialized up front. If you want any tween to start from a different initial value just use a from tween by calling _setFrom_ on the subsequent tweens. Example:

```
chain.appendTween(Text.transform.ZKlocalScaleTo(Vector3.one * 1.3f,0.5f));
chain.appendTween(Text.transform.ZKlocalScaleTo(Vector3.one * 1.0f,0.5f).setFrom( Vector3.one * 1.3f ));
chain.start();
```
